---
- name: Force password reset and temporary passwords
  hosts: all
  become: yes
  vars:
    temp_password: "Temp1234!"
  tasks:
    - name: Reset password for user
      user:
        name: "{{ item }}"
        password: "{{ temp_password | password_hash('sha512') }}"
        update_password: always
      with_items:
        - user1
        - user2

    - name: Force password change on next login
      command: chage -d 0 {{ item }}
      with_items:
        - user1
        - user2
