---
- name: Enforce Password Policies
  hosts: all
  become: yes
  tasks:
    - name: Ensure /etc/security directory exists
      file:
        path: /etc/security
        state: directory 
        mode: '0755' #permission for owner, group, and others

    - name: Ensure pwquality.conf file exists
      file:
        path: /etc/security/pwquality.conf
        state: touch
        mode: '0644'

    - name: Configure password history in PAM for password reuse
      lineinfile:
        path: /etc/pam.d/common-password
        regexp: "^#?password.*pam_unix.so.*remember="
        line: "password requisite pam_unix.so remember=5 use_authtok sha512"
        state: present

    - name: Enforce password complexity rules
      lineinfile:
        path: /etc/security/pwquality.conf
        regexp: "^#?minlen="
        line: "minlen = 12"
        state: present

    - name: Enforce password retry limit
      lineinfile:
        path: /etc/security/pwquality.conf
        regexp: "^#?retry="
        line: "retry = 3"
        state: present