---
- name: Configure Password Aging and Expiration
  hosts: all
  become: yes
  tasks:
    - name: Set default password expiration age
      lineinfile:
        path: /etc/login.defs
        regexp: "^PASS_MAX_DAYS"
        line: "PASS_MAX_DAYS   90"
        state: present

    - name: Set default password minimum age (days before password can be changed)
      lineinfile:
        path: /etc/login.defs
        regexp: "^PASS_MIN_DAYS"
        line: "PASS_MIN_DAYS   7"
        state: present

    - name: Set default password warning period
      lineinfile:
        path: /etc/login.defs
        regexp: "^PASS_WARN_AGE"
        line: "PASS_WARN_AGE   7"
        state: present

    - name: Enforce password expiration for specific user
      command: chage -M 30 -m 7 "{{ item }}"
      loop:
        - root

    - name: Ensure users are forced to change their passwords after initial login
      user:
        name: "{{ item }}"
        password_lock: yes
      loop:
        - root