---
- name: Enforce Password Complexity Requirements
  hosts: all
  become: yes
  tasks:
    - name: Ensure /etc/security directory exists
      file:
        path: /etc/security
        state: directory
        mode: '0755'

    - name: Ensure pwquality.conf file exists
      file:
        path: /etc/security/pwquality.conf
        state: touch
        mode: '0644'

    - name: Enforce password minimum length
      lineinfile:
        path: /etc/security/pwquality.conf
        regexp: "^#?minlen="
        line: "minlen = 12"
        state: present

    - name: Enforce minimum number of special characters
      lineinfile:
        path: /etc/security/pwquality.conf
        regexp: "^#?minspecial="
        line: "minspecial = 1"
        state: present

    - name: Enforce minimum number of upper case characters
      lineinfile:
        path: /etc/security/pwquality.conf
        regexp: "^#?minupper="
        line: "minupper = 1"
        state: present

    - name: Enforce minimum number of lower case characters
      lineinfile:
        path: /etc/security/pwquality.conf
        regexp: "^#?minlower="
        line: "minlower = 1"
        state: present

    - name: Enforce minimum number of digits
      lineinfile:
        path: /etc/security/pwquality.conf
        regexp: "^#?mindigit="
        line: "mindigit = 1"
        state: present

    - name: Enforce password retry limit
      lineinfile:
        path: /etc/security/pwquality.conf
        regexp: "^#?retry="
        line: "retry = 3"
        state: present
